### ISSUE TITLE
Response 401

### ISSUE THREAD

**Issue by tolid** [voxpupuli/webhook-go#122]
Hi 

I am trying to use webhook-go from our internal Gitlab server.

On Gitlab it is configured as http://servername:4000/api/v1/r10k/environment . However, it always returns code 401 and no changes pushed to the puppet server.
How can I debug this issue? On the puppet server in /var/log/syslog I can see only 
`Oct 28 15:13:59 sc384 webhook-go[48893]: [GIN] 2023/10/28 - 15:13:59 | 401 |      10.129µs |      10.1.68.21 | POST     "/api/v1/r10k/environment"`

Webhook configuration (/etc/voxpupuli/webhook.yml):
```
server:
  protected: true
  user: puppet
  password: puppet
  port: 4000
  tls:
    enabled: false
    certificate: ""
    key: ""
chatops:
  enabled: false
  service: slack
  channel: "#general"
  user: r10kbot
  auth_token: 12345
  server_uri: "https://rocketchat.local"
r10k:
  config_path: /etc/puppetlabs/r10k/r10k.yaml
  default_branch: webhook_test
  allow_uppercase: false
  verbose: true
  generate_types: false
```

Could you please advise how to debug this? Enable extra logging etc?
