### ISSUE TITLE
Gitea "unknown event type" (create and delete)

### ISSUE THREAD

**Issue by posledov** [voxpupuli/webhook-go#175]
Gitea version :: 1.22.3
webhook-go version :: 2.2.0

`cat /etc/voxpupuli/webhook.yml`
```yaml
---
server:
  protected: false
  port: 8088
chatops:
  enabled: false
  service:
  channel:
  user:
  auth_token:
  server_uri:
r10k:
  command_path: "/opt/puppetlabs/puppet/bin/r10k"
  config_path: "/etc/puppetlabs/r10k/r10k.yaml"
  default_branch: production
  prefix:
  allow_uppercase: false
  verbose: true
  deploy_modules: true
  generate_types: false
```

Creating or deleting a branch leads to the following errors:

```
жов 13 18:43:52 puppet.local.lan webhook-go[111824]: time="2024-10-13T18:43:52+03:00" level=error msg="error parsing webhook: unknown event type delete"
жов 13 18:43:52 puppet.local.lan webhook-go[111824]: [GIN] 2024/10/13 - 18:43:52 | 500 |    6.828339ms |  192.168.1.13 | POST     "/api/v1/r10k/environment"
жов 13 18:44:51 puppet.local.lan webhook-go[111824]: time="2024-10-13T18:44:51+03:00" level=error msg="error parsing webhook: unknown event type create"
жов 13 18:44:51 puppet.local.lan webhook-go[111824]: [GIN] 2024/10/13 - 18:44:51 | 500 |     290.667µs |  192.168.1.13 | POST     "/api/v1/r10k/environment"
```
