### ISSUE TITLE
prefix of "repo" does not seem to apply

### ISSUE THREAD

**Issue by damonmaria** [voxpupuli/webhook-go#201]
Looking at the code for the `GetPrefix` function, it would appear that setting the `prefix` in configuration to `"repo"` would prefix the environment with the repo name. This is exactly what we need (we manage many different repos with the one server).

But when I try that in production I can see the environment name the webhook has built is `repo_production`. I also can't see `GetPrefix` being used (apart from in tests) in the codebase. 

Using the repo name as a prefix would be a workable solution for us until #115 comes along. Can this feature (as I'm guessing it's supposed to work) be enabled?

**Comment by damonmaria** [comment]
> Hey, can you show your r10k config file? It has an option to set the prefix.

That is setup in r10k.yaml. See below.

```
---
pool_size: 4
git:
  provider: shellgit
deploy:
  purge_levels:
  - deployment
  - environment
  - puppetfile
  generate_types: true
cachedir: "/opt/puppetlabs/puppet/cache/r10k"
sources:
  devops:
    remote: git@github.com:*******/devops-control.git
    basedir: "/etc/puppetlabs/code/environments"
    prefix: true
  foo:
    remote: git@github.com::*******/:foo-control.git
    basedir: "/etc/puppetlabs/code/environments"
    prefix: true
...
```

But when webhook-go tries to call r10k it is not prefixing the environment it calls with. Here's from the logs of the webhook-go.service:
```
failed to execute local command `[/opt/puppetlabs/puppet/bin/r10k deploy environment production --config=/etc/puppetlabs/r10k/r10k.yaml --verbose --generate-types --modules]` 
with error: `exit status 1` 
`ERROR	 -> Environment(s) 'production' cannot be found in any source and will not be deployed.`
```

Note the passed environment is `production` without a prefix. 

After seeing the code in `Helpers.GetPrefix` I had thought setting the `r10k/prefix` in `/etc/voxpupuli/webhook.yml` to `prefix: 'repo'` would have changed this failed call to call with an environment based on the repo name, something like (from my example above) `devops_control_production`. But instead I got: 
```
failed to execute local command `[/opt/puppetlabs/puppet/bin/r10k deploy environment repo_production --config=/etc/puppetlabs/r10k/r10k.yaml --verbose --generate-types --modules]` 
with error: `exit status 1` 
`ERROR -> Environment(s) 'repo_production' cannot be found in any source and will not be deployed.`
```

Am I doing something incorrectly?
